### ISSUE TITLE
On clean verify, `usb_mouse_move` and `usb_mouse_buttons_state` are not declared.

### ISSUE THREAD

**Issue by NessDan** [Trip93/teensy4_mouse#1]
Context: [Followed these steps.](https://www.pjrc.com/teensy/td_download.html) I have a fresh install of the Arduino 2.1.0 IDE and installed the Teensy board.

Downloaded and ran the project, only to get some issues:

```
C:\Users\danie\Downloads\teensy4_mouse-main\teensy4_mouse-main\teensy4_mouse\teensy4_mouse.ino: In function 'void update_usb()':
C:\Users\danie\Downloads\teensy4_mouse-main\teensy4_mouse-main\teensy4_mouse\teensy4_mouse.ino:261:61: warning: operation on 'scroll' may be undefined [-Wsequence-point]
  261 |   int8_t scroll           = (buttons & 0b10000000) ? scroll =  1 : (buttons & 0b01000000) ? scroll = -1 : scroll = 0;
      |                                                      ~~~~~~~^~~~
C:\Users\danie\Downloads\teensy4_mouse-main\teensy4_mouse-main\teensy4_mouse\teensy4_mouse.ino:262:3: error: 'usb_mouse_buttons_state' was not declared in this scope
  262 |   usb_mouse_buttons_state =  buttons;
      |   ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\danie\Downloads\teensy4_mouse-main\teensy4_mouse-main\teensy4_mouse\teensy4_mouse.ino:267:3: error: 'usb_mouse_move' was not declared in this scope
  267 |   usb_mouse_move(x, y, scroll, 0);
      |   ^~~~~~~~~~~~~~

exit status 1

Compilation error: 'usb_mouse_buttons_state' was not declared in this scope
```

I went ahead and did some Googling and found [`usb_mouse_move` defined in this library](https://github.com/PaulStoffregen/cores/blob/master/teensy4/usb_mouse.h).

**Comment by NessDan** [comment]
Not exactly sure which one of these things fixed it but,

1. Installed Arduino 1.8.19 legacy
2. Downloaded the "TeensyduinoInstall.exe" file and installed to the Arduino folder
3. Tools ->  USB type: Keyboard + Mouse + Joystick

After that it compiled successfully! Have to still hook it up, but closing this for now.

**Comment by Trip93** [comment]
I was about to send a reply but yes most likely the USB type fixed it.
Selecting that will enable the library path for that function.
